### ISSUE TITLE
Error when trying to build a container for development environment

### ISSUE THREAD

**Issue by Oktopuce** [fnagel/docker-typo3#2]
When I run this command to build a container for development environment : 

> docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

I have this error : 

> pull access denied for fnagel/docker-typo3-webserver, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ERROR: Service 'webserver' failed to build : Build failed

**Comment by fnagel** [comment]
@Oktopuce Did you run `docker-compose -f docker-compose.yml` before? You need to create the base image in order to use it when creating the dev image.

**Comment by Oktopuce** [comment]
Try to run this command : 

> docker-compose -f docker-compose.yml build

and the result is : 

> ### INSTALLING REMOTE MODULE mysql ###
> No releases available for package "pecl.php.net/mysql"
> install failed
> The command '/bin/sh -c install-php-extensions bcmath zip exif gd mysql mysqli pdo pdo_mysql intl soap opcache' returned a non-zero code: 1
> ERROR: Service 'webserver' failed to build : Build failed
>

**Comment by fnagel** [comment]
What about `docker-compose build`? Should be the same, but you never know. 

Might be an issue with the latest commit: 2924532cc247fde164ab9a627dbb326ec5e68d18
You might want to try it when reversed.

**Comment by Oktopuce** [comment]
Yes it's the same with "docker-compose build", already tried.

**Comment by fnagel** [comment]
Damn. Looks like `mysql` is outdated. See https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions

Please try with this line in above mentioned line:
`RUN install-php-extensions bcmath zip exif gd mysqli pdo pdo_mysql intl soap opcache`

**Comment by Oktopuce** [comment]
Yes it works with this line.
